name: Log Click Event

on:
  repository_dispatch:
    types:
      - log_click

jobs:
  log_click:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Ensure the log file exists
      - name: Prepare Log File
        run: |
          if [ ! -f click_log.json ]; then
            echo "[]" > click_log.json
          fi

      # Debugging Step: Output client_payload
      - name: Debug Client Payload
        run: echo '${{ toJson(github.event.client_payload) }}'

      # Append the new data to the log file
      - name: Append Click Event to Log
        run: |
          if [ ! -f click_log.json ]; then
            echo "[]" > click_log.json
          fi
          echo '${{ toJson(github.event.client_payload) }}' | \
          jq '. as $newEvent | input | . + [$newEvent]' click_log.json > temp.json
          mv temp.json click_log.json

      # Commit and push changes back to the repository
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your GitHub Username"
          git add click_log.json
          git commit -m "Log click event"
          git push
