name: Log UTM Clicks

on:
  repository_dispatch:
    types:
      - log_click

jobs:
  log_click:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Ensure click_log.json exists
      - name: Prepare Log File
        run: |
          if [ ! -f click_log.json ]; then
            echo "[]" > click_log.json
          fi

      # Append the new UTM link to the log
      - name: Append UTM Link to Log
        run: |
          echo '${{ toJson(github.event.client_payload) }}' | \
          jq '. as $newEvent | $existing + [$newEvent]' --slurpfile existing click_log.json | jq 'flatten(1)' > temp.json
          mv temp.json click_log.json

      # Commit and push updates
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add click_log.json
          git commit -m "Log UTM link"
          git push origin HEAD
