name: Update Link Counts

on:
  repository_dispatch:
    types:
      - log_click
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  update_counts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Ensure click_log.json exists
      - name: Prepare Log File
        run: |
          if [ ! -f click_log.json ]; then
            echo "[]" > click_log.json
          fi

      # Step 3: Count clicks by link
      - name: Count Clicks by Link
        run: |
          jq -r 'map(.target_url) | group_by(.) | map({link: .[0], count: length})' click_log.json > link_counts.json

      # Step 4: Generate an HTML page
      - name: Generate HTML Page
        run: |
          echo '<html><body><h1>Link Click Counts</h1><ul>' > link_counts.html
          jq -r '.[] | "<li>\(.link): \(.count) clicks</li>"' link_counts.json >> link_counts.html
          echo '</ul></body></html>' >> link_counts.html

      # Step 5: Commit and push updates
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add click_log.json link_counts.json link_counts.html
          git commit -m "Daily update: Link counts"
          git push origin HEAD
